### ISSUE TITLE
How can I get the other 2 datasets?

### ISSUE THREAD

**Issue by rayrayraykk** [eXascaleInfolab/JUST#1]
There are only about 2000 author labled in the DBLP dataset you give,and I change the m form 1 to 3,and I get the result as follows：
`Epoch:5000,Loss:0.9261,Accuracy：0.89,micro-f1:0.8901,macro-f1:0.8889 `
Now I want to test the other 2 datasets and larger KG，like Freebase，how can I obtain the datasets，or in other word，can you offer the datasets？
What's more，will JUST work as good as DBLP in Freebase or Wordnet？

**Comment by ranahussein** [comment]
I updated foursquare and movies datasets in the dataset directory.
We haven’t tested JUST on KGs.

**Comment by rayrayraykk** [comment]
> I updated foursquare and movies datasets in the dataset directory.
> We haven’t tested JUST on KGs.

Thanks
