### ISSUE TITLE
How to use the DBLP dataset？

### ISSUE THREAD

**Issue by woshiyitongshui** [eXascaleInfolab/JUST#5]
Hello, I download the dataset from the website, but I don't know how to transform it to the dataset that can be uesd with python.

**Comment by ranahussein** [comment]
Hello, you can directly read the dataset in your python code using the read_edgelist function from networkx library.

**Comment by woshiyitongshui** [comment]
> Hello, you can directly read the dataset in your python code using the read_edgelist function from networkx library.

Thank you very much.
